### ISSUE TITLE
Build Linux binaries and allow install with Homebrew?

### ISSUE THREAD

**Issue by yermulnik** [ikebastuz/wiper#25]
```shell
> brew tap ikebastuz/wiper
==> Auto-updating Homebrew...
==> Tapping ikebastuz/wiper
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/ikebastuz/homebrew-wiper'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 33 (delta 7), reused 33 (delta 7), pack-reused 0
Receiving objects: 100% (33/33), done.
Resolving deltas: 100% (7/7), done.
Tapped 1 formula (14 files, 71.7KB).

> brew install wiper
==> Auto-updating Homebrew...
Error: formulae require at least a URL
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:316:in `determine_active_spec'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:249:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:570:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:570:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:794:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:1009:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:146:in `block in load_formula_or_cask'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/api.rb:204:in `with_no_api_env_if_needed'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:138:in `load_formula_or_cask'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:81:in `block in to_formulae_and_casks'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:79:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:79:in `flat_map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:79:in `to_formulae_and_casks'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:196:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

Would be great to allow Linux users to also leverage `wiper` bu shipping Linux binaries and also to use Homebrew to install it. Thanks in advance.

**Comment by ikebastuz** [comment]
Hello, thank you so much for reporting!
I'm pretty new to rust and not very familiar with whole build ecosystem, but I'm very keen to try.

I managed to build something and added binaries to release aswell as to brew formula. Can you give it a try and let me know if it helps?

Just keep in mind, that homebrew might require re-tapping formula, i.e.
```bash
brew untap ikebastuz/wiper
brew tap ikebastuz/wiper
brew install wiper
```

Otherwise it might keep using already downloaded formula

**Comment by yermulnik** [comment]
@ikebastuz Worked w/o re-tapping:
```shell
> brew install wiper
==> Auto-updating Homebrew...
==> Fetching ikebastuz/wiper/wiper
==> Downloading https://github.com/ikebastuz/wiper/releases/download/v0.2.1/wiper-x86_64-unknown-lin
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/79
############################################################################################# 100.0%
==> Installing wiper from ikebastuz/wiper
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
✔  /home/linuxbrew/.linuxbrew/Cellar/wiper/0.2.1: 4 files, 5MB, built in 1 second
==> Running `brew cleanup wiper`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```
The `tar` warning I have never seen, though it doesn't break install.
Thanks for looking into this and add Linux with Homebrew support.

**Comment by ikebastuz** [comment]
Thank you for confirming it!

Stackoverflow says this warning is ok-ish :)

<img width="743" alt="image" src="https://github.com/ikebastuz/wiper/assets/24222413/dbb366b3-01dd-4b64-b811-6f8ea2d12b0a">

https://stackoverflow.com/questions/51655657/tar-ignoring-unknown-extended-header-keyword-libarchive-xattr-security-selinux
